# Job Application Pipeline Configuration
version: '1.0'
name: "Job Application Pipeline"
description: "Automated job application submission for multiple job portals"

# Global settings
global:
  headless: false  # Set to true for production
  timeout: 120000  # Increased timeout to 120 seconds
  viewport: { width: 1280, height: 2000 }
  userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

# List of tasks to execute for each job URL
tasks:
  # Task 1: Navigate to the job URL
  - name: "Navigate to Job Page"
    type: "navigate"
    url: "${jobUrl}"
    waitUntil: "domcontentloaded"  # Wait for DOM content to load
    timeout: 120000  # 2 minutes timeout
    waitForTimeout: 3000  # Wait 3 seconds after navigation

  # Task 2: Accept cookies if the banner appears
  - name: "Accept Cookies"
    type: "click"
    selector: "button:has-text('Alle akzeptieren'), button:has-text('Accept all'), button:has-text('Akzeptieren'), [id*='cookie'], [class*='cookie'] button"
    timeout: 10000  # Increased timeout to 10 seconds
    optional: true
    waitForTimeout: 1000  # Wait 1 second after clicking

  # Task 3: Click on Apply Now button if it exists
  - name: "Click Apply Now"
    type: "click"
    selector: "button:has-text('Jetzt bewerben'), button:has-text('Apply now'), a:has-text('Jetzt bewerben'), a:has-text('Apply now')"
    optional: true
    timeout: 10000
    waitForNavigation: true

  # Task 4: Fill in personal information
  - name: "Fill Personal Information"
    type: "fill"
    timeout: 15000  # 15 seconds timeout for the entire form
    fields:
      - name: "First Name"
        selector: "#firstName"
        value: "${user.firstName}"
        optional: false
      
      - name: "Last Name"
        selector: "#lastName"
        value: "${user.lastName}"
        optional: false
      
      - name: "Email"
        selector: "#email"
        value: "${user.email}"
        optional: false
      
      - name: "Phone"
        selector: "#telephone"
        value: "${user.phone}"
        optional: true
      
      - name: "Cover Letter"
        selector: "textarea, [role='textbox'], .ql-editor, [class*='text-editor'], [id*='message'], [id*='coverLetter'], [name*='coverLetter']"
        value: "${user.coverLetter}"
        optional: true
        timeout: 5000  # Shorter timeout since it's optional

  # Task 5: Upload CV and cover letter
  - name: "Upload Documents"
    type: "upload"
    selector: "input[type='file'], [class*='upload'], .file-upload"
    file: "${paths.cv}"
    optional: true
    timeout: 30000  # 30 seconds for file upload

  # Task 6: Submit the application
  - name: "Submit Application"
    type: "click"
    selector: "button[type='submit'], button:has-text('Bewerbung absenden'), button:has-text('Submit Application')"
    waitForNavigation: true
    optional: false

# Default values that can be overridden
defaults:
  user:
    firstName: "Jan"
    lastName: "Kowalski"
    email: "jan.kowalski@example.com"
    phone: "+48123456789"
    coverLetter: |
      Sehr geehrtes Team,

      hiermit bewerbe ich mich auf die ausgeschriebene Stelle. 
      Meine vollständigen Unterlagen finden Sie im Anhang.

      Mit freundlichen Grüßen,
      ${user.firstName} ${user.lastName}
  paths:
    cv: "./documents/cv.pdf"
    coverLetter: "./documents/cover_letter.pdf"
